// src/data/countries.js
const COUNTRIES = [
  { name: "Nigeria", nationality: "Nigerian", isoCode: "NG", phoneCode: "+234", flag: "🇳🇬" },
  { name: "United States", nationality: "American", isoCode: "US", phoneCode: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", nationality: "British", isoCode: "GB", phoneCode: "+44", flag: "🇬🇧" },
  { name: "Afghanistan", nationality: "Afghan", isoCode: "AF", phoneCode: "+93", flag: "🇦🇫" },
  { name: "Albania", nationality: "Albanian", isoCode: "AL", phoneCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", nationality: "Algerian", isoCode: "DZ", phoneCode: "+213", flag: "🇩🇿" },
  { name: "Andorra", nationality: "Andorran", isoCode: "AD", phoneCode: "+376", flag: "🇦🇩" },
  { name: "Angola", nationality: "Angolan", isoCode: "AO", phoneCode: "+244", flag: "🇦🇴" },
  { name: "Argentina", nationality: "Argentinean", isoCode: "AR", phoneCode: "+54", flag: "🇦🇷" },
  { name: "Armenia", nationality: "Armenian", isoCode: "AM", phoneCode: "+374", flag: "🇦🇲" },
  { name: "Australia", nationality: "Australian", isoCode: "AU", phoneCode: "+61", flag: "🇦🇺" },
  { name: "Austria", nationality: "Austrian", isoCode: "AT", phoneCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", nationality: "Azerbaijani", isoCode: "AZ", phoneCode: "+994", flag: "🇦🇿" },
  { name: "Bahamas", nationality: "Bahamian", isoCode: "BS", phoneCode: "+1-242", flag: "🇧🇸" },
  { name: "Bahrain", nationality: "Bahraini", isoCode: "BH", phoneCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", nationality: "Bangladeshi", isoCode: "BD", phoneCode: "+880", flag: "🇧🇩" },
  { name: "Barbados", nationality: "Barbadian", isoCode: "BB", phoneCode: "+1-246", flag: "🇧🇧" },
  { name: "Belarus", nationality: "Belarusian", isoCode: "BY", phoneCode: "+375", flag: "🇧🇾" },
  { name: "Belgium", nationality: "Belgian", isoCode: "BE", phoneCode: "+32", flag: "🇧🇪" },
  { name: "Belize", nationality: "Belizean", isoCode: "BZ", phoneCode: "+501", flag: "🇧🇿" },
  { name: "Benin", nationality: "Beninese", isoCode: "BJ", phoneCode: "+229", flag: "🇧🇯" },
  { name: "Bhutan", nationality: "Bhutanese", isoCode: "BT", phoneCode: "+975", flag: "🇧🇹" },
  { name: "Bolivia", nationality: "Bolivian", isoCode: "BO", phoneCode: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", nationality: "Bosnian", isoCode: "BA", phoneCode: "+387", flag: "🇧🇦" },
  { name: "Botswana", nationality: "Botswanan", isoCode: "BW", phoneCode: "+267", flag: "🇧🇼" },
  { name: "Brazil", nationality: "Brazilian", isoCode: "BR", phoneCode: "+55", flag: "🇧🇷" },
  { name: "Brunei", nationality: "Bruneian", isoCode: "BN", phoneCode: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", nationality: "Bulgarian", isoCode: "BG", phoneCode: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", nationality: "Burkinabe", isoCode: "BF", phoneCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", nationality: "Burundian", isoCode: "BI", phoneCode: "+257", flag: "🇧🇮" },
  { name: "Cabo Verde", nationality: "Cabo Verdean", isoCode: "CV", phoneCode: "+238", flag: "🇨🇻" },
  { name: "Cambodia", nationality: "Cambodian", isoCode: "KH", phoneCode: "+855", flag: "🇰🇭" },
  { name: "Cameroon", nationality: "Cameroonian", isoCode: "CM", phoneCode: "+237", flag: "🇨🇲" },
  { name: "Canada", nationality: "Canadian", isoCode: "CA", phoneCode: "+1", flag: "🇨🇦" },
  { name: "Central African Republic", nationality: "Central African", isoCode: "CF", phoneCode: "+236", flag: "🇨🇫" },
  { name: "Chad", nationality: "Chadian", isoCode: "TD", phoneCode: "+235", flag: "🇹🇩" },
  { name: "Chile", nationality: "Chilean", isoCode: "CL", phoneCode: "+56", flag: "🇨🇱" },
  { name: "China", nationality: "Chinese", isoCode: "CN", phoneCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", nationality: "Colombian", isoCode: "CO", phoneCode: "+57", flag: "🇨🇴" },
  { name: "Comoros", nationality: "Comoran", isoCode: "KM", phoneCode: "+269", flag: "🇰🇲" },
  { name: "Congo", nationality: "Congolese", isoCode: "CG", phoneCode: "+242", flag: "🇨🇬" },
  { name: "Costa Rica", nationality: "Costa Rican", isoCode: "CR", phoneCode: "+506", flag: "🇨🇷" },
  { name: "Croatia", nationality: "Croatian", isoCode: "HR", phoneCode: "+385", flag: "🇭🇷" },
  { name: "Cuba", nationality: "Cuban", isoCode: "CU", phoneCode: "+53", flag: "🇨🇺" },
  { name: "Cyprus", nationality: "Cypriot", isoCode: "CY", phoneCode: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", nationality: "Czech", isoCode: "CZ", phoneCode: "+420", flag: "🇨🇿" },
  { name: "Denmark", nationality: "Danish", isoCode: "DK", phoneCode: "+45", flag: "🇩🇰" },
  { name: "Djibouti", nationality: "Djiboutian", isoCode: "DJ", phoneCode: "+253", flag: "🇩🇯" },
  { name: "Dominica", nationality: "Dominican", isoCode: "DM", phoneCode: "+1-767", flag: "🇩🇲" },
  { name: "Dominican Republic", nationality: "Dominican", isoCode: "DO", phoneCode: "+1-809", flag: "🇩🇴" },
  { name: "Ecuador", nationality: "Ecuadorean", isoCode: "EC", phoneCode: "+593", flag: "🇪🇨" },
  { name: "Egypt", nationality: "Egyptian", isoCode: "EG", phoneCode: "+20", flag: "🇪🇬" },
  { name: "El Salvador", nationality: "Salvadoran", isoCode: "SV", phoneCode: "+503", flag: "🇸🇻" },
  { name: "Equatorial Guinea", nationality: "Equatorial Guinean", isoCode: "GQ", phoneCode: "+240", flag: "🇬🇶" },
  { name: "Eritrea", nationality: "Eritrean", isoCode: "ER", phoneCode: "+291", flag: "🇪🇷" },
  { name: "Estonia", nationality: "Estonian", isoCode: "EE", phoneCode: "+372", flag: "🇪🇪" },
  { name: "Eswatini", nationality: "Swazi", isoCode: "SZ", phoneCode: "+268", flag: "🇸🇿" },
  { name: "Ethiopia", nationality: "Ethiopian", isoCode: "ET", phoneCode: "+251", flag: "🇪🇹" },
  { name: "Fiji", nationality: "Fijian", isoCode: "FJ", phoneCode: "+679", flag: "🇫🇯" },
  { name: "Finland", nationality: "Finnish", isoCode: "FI", phoneCode: "+358", flag: "🇫🇮" },
  { name: "France", nationality: "French", isoCode: "FR", phoneCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", nationality: "Gabonese", isoCode: "GA", phoneCode: "+241", flag: "🇬🇦" },
  { name: "Gambia", nationality: "Gambian", isoCode: "GM", phoneCode: "+220", flag: "🇬🇲" },
  { name: "Georgia", nationality: "Georgian", isoCode: "GE", phoneCode: "+995", flag: "🇬🇪" },
  { name: "Germany", nationality: "German", isoCode: "DE", phoneCode: "+49", flag: "🇩🇪" },
  { name: "Ghana", nationality: "Ghanaian", isoCode: "GH", phoneCode: "+233", flag: "🇬🇭" },
  { name: "Greece", nationality: "Greek", isoCode: "GR", phoneCode: "+30", flag: "🇬🇷" },
  { name: "Grenada", nationality: "Grenadian", isoCode: "GD", phoneCode: "+1-473", flag: "🇬🇩" },
  { name: "Guatemala", nationality: "Guatemalan", isoCode: "GT", phoneCode: "+502", flag: "🇬🇹" },
  { name: "Guinea", nationality: "Guinean", isoCode: "GN", phoneCode: "+224", flag: "🇬🇳" },
  { name: "Guinea-Bissau", nationality: "Guinea-Bissauan", isoCode: "GW", phoneCode: "+245", flag: "🇬🇼" },
  { name: "Guyana", nationality: "Guyanese", isoCode: "GY", phoneCode: "+592", flag: "🇬🇾" },
  { name: "Haiti", nationality: "Haitian", isoCode: "HT", phoneCode: "+509", flag: "🇭🇹" },
  { name: "Honduras", nationality: "Honduran", isoCode: "HN", phoneCode: "+504", flag: "🇭🇳" },
  { name: "Hungary", nationality: "Hungarian", isoCode: "HU", phoneCode: "+36", flag: "🇭🇺" },
  { name: "Iceland", nationality: "Icelandic", isoCode: "IS", phoneCode: "+354", flag: "🇮🇸" },
  { name: "India", nationality: "Indian", isoCode: "IN", phoneCode: "+91", flag: "🇮🇳" },
  { name: "Indonesia", nationality: "Indonesian", isoCode: "ID", phoneCode: "+62", flag: "🇮🇩" },
  { name: "Iran", nationality: "Iranian", isoCode: "IR", phoneCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", nationality: "Iraqi", isoCode: "IQ", phoneCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", nationality: "Irish", isoCode: "IE", phoneCode: "+353", flag: "🇮🇪" },
  { name: "Israel", nationality: "Israeli", isoCode: "IL", phoneCode: "+972", flag: "🇮🇱" },
  { name: "Italy", nationality: "Italian", isoCode: "IT", phoneCode: "+39", flag: "🇮🇹" },
  { name: "Jamaica", nationality: "Jamaican", isoCode: "JM", phoneCode: "+1-876", flag: "🇯🇲" },
  { name: "Japan", nationality: "Japanese", isoCode: "JP", phoneCode: "+81", flag: "🇯🇵" },
  { name: "Jordan", nationality: "Jordanian", isoCode: "JO", phoneCode: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", nationality: "Kazakhstani", isoCode: "KZ", phoneCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", nationality: "Kenyan", isoCode: "KE", phoneCode: "+254", flag: "🇰🇪" },
  { name: "Kiribati", nationality: "I-Kiribati", isoCode: "KI", phoneCode: "+686", flag: "🇰🇮" },
  { name: "Korea, North", nationality: "North Korean", isoCode: "KP", phoneCode: "+850", flag: "🇰🇵" },
  { name: "Korea, South", nationality: "South Korean", isoCode: "KR", phoneCode: "+82", flag: "🇰🇷" },
  { name: "Kuwait", nationality: "Kuwaiti", isoCode: "KW", phoneCode: "+965", flag: "🇰🇼" },
  { name: "Kyrgyzstan", nationality: "Kyrgyz", isoCode: "KG", phoneCode: "+996", flag: "🇰🇬" },
  { name: "Laos", nationality: "Laotian", isoCode: "LA", phoneCode: "+856", flag: "🇱🇦" },
  { name: "Latvia", nationality: "Latvian", isoCode: "LV", phoneCode: "+371", flag: "🇱🇻" },
  { name: "Lebanon", nationality: "Lebanese", isoCode: "LB", phoneCode: "+961", flag: "🇱🇧" },
  { name: "Lesotho", nationality: "Mosotho", isoCode: "LS", phoneCode: "+266", flag: "🇱🇸" },
  { name: "Liberia", nationality: "Liberian", isoCode: "LR", phoneCode: "+231", flag: "🇱🇷" },
  { name: "Libya", nationality: "Libyan", isoCode: "LY", phoneCode: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", nationality: "Liechtensteiner", isoCode: "LI", phoneCode: "+423", flag: "🇱🇮" },
  { name: "Lithuania", nationality: "Lithuanian", isoCode: "LT", phoneCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", nationality: "Luxembourger", isoCode: "LU", phoneCode: "+352", flag: "🇱🇺" },
  { name: "Madagascar", nationality: "Malagasy", isoCode: "MG", phoneCode: "+261", flag: "🇲🇬" },
  { name: "Malawi", nationality: "Malawian", isoCode: "MW", phoneCode: "+265", flag: "🇲🇼" },
  { name: "Malaysia", nationality: "Malaysian", isoCode: "MY", phoneCode: "+60", flag: "🇲🇾" },
  { name: "Maldives", nationality: "Maldivan", isoCode: "MV", phoneCode: "+960", flag: "🇲🇻" },
  { name: "Mali", nationality: "Malian", isoCode: "ML", phoneCode: "+223", flag: "🇲🇱" },
  { name: "Malta", nationality: "Maltese", isoCode: "MT", phoneCode: "+356", flag: "🇲🇹" },
  { name: "Marshall Islands", nationality: "Marshallese", isoCode: "MH", phoneCode: "+692", flag: "🇲🇭" },
  { name: "Mauritania", nationality: "Mauritanian", isoCode: "MR", phoneCode: "+222", flag: "🇲🇷" },
  { name: "Mauritius", nationality: "Mauritian", isoCode: "MU", phoneCode: "+230", flag: "🇲🇺" },
  { name: "Mexico", nationality: "Mexican", isoCode: "MX", phoneCode: "+52", flag: "🇲🇽" },
  { name: "Micronesia", nationality: "Micronesian", isoCode: "FM", phoneCode: "+691", flag: "🇫🇲" },
  { name: "Moldova", nationality: "Moldovan", isoCode: "MD", phoneCode: "+373", flag: "🇲🇩" },
  { name: "Monaco", nationality: "Monacan", isoCode: "MC", phoneCode: "+377", flag: "🇲🇨" },
  { name: "Mongolia", nationality: "Mongolian", isoCode: "MN", phoneCode: "+976", flag: "🇲🇳" },
  { name: "Montenegro", nationality: "Montenegrin", isoCode: "ME", phoneCode: "+382", flag: "🇲🇪" },
  { name: "Morocco", nationality: "Moroccan", isoCode: "MA", phoneCode: "+212", flag: "🇲🇦" },
  { name: "Mozambique", nationality: "Mozambican", isoCode: "MZ", phoneCode: "+258", flag: "🇲🇿" },
  { name: "Myanmar", nationality: "Burmese", isoCode: "MM", phoneCode: "+95", flag: "🇲🇲" },
  { name: "Namibia", nationality: "Namibian", isoCode: "NA", phoneCode: "+264", flag: "🇳🇦" },
  { name: "Nauru", nationality: "Nauruan", isoCode: "NR", phoneCode: "+674", flag: "🇳🇷" },
  { name: "Nepal", nationality: "Nepalese", isoCode: "NP", phoneCode: "+977", flag: "🇳🇵" },
  { name: "Netherlands", nationality: "Dutch", isoCode: "NL", phoneCode: "+31", flag: "🇳🇱" },
  { name: "New Zealand", nationality: "New Zealander", isoCode: "NZ", phoneCode: "+64", flag: "🇳🇿" },
  { name: "Nicaragua", nationality: "Nicaraguan", isoCode: "NI", phoneCode: "+505", flag: "🇳🇮" },
  { name: "Niger", nationality: "Nigerien", isoCode: "NE", phoneCode: "+227", flag: "🇳🇪" },
  { name: "North Macedonia", nationality: "Macedonian", isoCode: "MK", phoneCode: "+389", flag: "🇲🇰" },
  { name: "Norway", nationality: "Norwegian", isoCode: "NO", phoneCode: "+47", flag: "🇳🇴" },
  { name: "Oman", nationality: "Omani", isoCode: "OM", phoneCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", nationality: "Pakistani", isoCode: "PK", phoneCode: "+92", flag: "🇵🇰" },
  { name: "Palau", nationality: "Palauan", isoCode: "PW", phoneCode: "+680", flag: "🇵🇼" },
  { name: "Panama", nationality: "Panamanian", isoCode: "PA", phoneCode: "+507", flag: "🇵🇦" },
  { name: "Papua New Guinea", nationality: "Papua New Guinean", isoCode: "PG", phoneCode: "+675", flag: "🇵🇬" },
  { name: "Paraguay", nationality: "Paraguayan", isoCode: "PY", phoneCode: "+595", flag: "🇵🇾" },
  { name: "Peru", nationality: "Peruvian", isoCode: "PE", phoneCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", nationality: "Filipino", isoCode: "PH", phoneCode: "+63", flag: "🇵🇭" },
  { name: "Poland", nationality: "Polish", isoCode: "PL", phoneCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", nationality: "Portuguese", isoCode: "PT", phoneCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", nationality: "Qatari", isoCode: "QA", phoneCode: "+974", flag: "🇶🇦" },
  { name: "Romania", nationality: "Romanian", isoCode: "RO", phoneCode: "+40", flag: "🇷🇴" },
  { name: "Russia", nationality: "Russian", isoCode: "RU", phoneCode: "+7", flag: "🇷🇺" },
  { name: "Rwanda", nationality: "Rwandan", isoCode: "RW", phoneCode: "+250", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", nationality: "Kittian and Nevisian", isoCode: "KN", phoneCode: "+1-869", flag: "🇰🇳" },
  { name: "Saint Lucia", nationality: "Saint Lucian", isoCode: "LC", phoneCode: "+1-758", flag: "🇱🇨" },
  { name: "Samoa", nationality: "Samoan", isoCode: "WS", phoneCode: "+685", flag: "🇼🇸" },
  { name: "San Marino", nationality: "San Marinese", isoCode: "SM", phoneCode: "+378", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", nationality: "Sao Tomean", isoCode: "ST", phoneCode: "+239", flag: "🇸🇹" },
  { name: "Saudi Arabia", nationality: "Saudi", isoCode: "SA", phoneCode: "+966", flag: "🇸🇦" },
  { name: "Senegal", nationality: "Senegalese", isoCode: "SN", phoneCode: "+221", flag: "🇸🇳" },
  { name: "Serbia", nationality: "Serbian", isoCode: "RS", phoneCode: "+381", flag: "🇷🇸" },
  { name: "Seychelles", nationality: "Seychellois", isoCode: "SC", phoneCode: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", nationality: "Sierra Leonean", isoCode: "SL", phoneCode: "+232", flag: "🇸🇱" },
  { name: "Singapore", nationality: "Singaporean", isoCode: "SG", phoneCode: "+65", flag: "🇸🇬" },
  { name: "Slovakia", nationality: "Slovak", isoCode: "SK", phoneCode: "+421", flag: "🇸🇰" },
  { name: "Slovenia", nationality: "Slovenian", isoCode: "SI", phoneCode: "+386", flag: "🇸🇮" },
  { name: "Solomon Islands", nationality: "Solomon Islander", isoCode: "SB", phoneCode: "+677", flag: "🇸🇧" },
  { name: "Somalia", nationality: "Somali", isoCode: "SO", phoneCode: "+252", flag: "🇸🇴" },
  { name: "South Africa", nationality: "South African", isoCode: "ZA", phoneCode: "+27", flag: "🇿🇦" },
  { name: "South Sudan", nationality: "South Sudanese", isoCode: "SS", phoneCode: "+211", flag: "🇸🇸" },
  { name: "Spain", nationality: "Spanish", isoCode: "ES", phoneCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", nationality: "Sri Lankan", isoCode: "LK", phoneCode: "+94", flag: "🇱🇰" },
  { name: "Sudan", nationality: "Sudanese", isoCode: "SD", phoneCode: "+249", flag: "🇸🇩" },
  { name: "Suriname", nationality: "Surinamer", isoCode: "SR", phoneCode: "+597", flag: "🇸🇷" },
  { name: "Sweden", nationality: "Swedish", isoCode: "SE", phoneCode: "+46", flag: "🇸🇪" },
  { name: "Switzerland", nationality: "Swiss", isoCode: "CH", phoneCode: "+41", flag: "🇨🇭" },
  { name: "Syria", nationality: "Syrian", isoCode: "SY", phoneCode: "+963", flag: "🇸🇾" },
  { name: "Taiwan", nationality: "Taiwanese", isoCode: "TW", phoneCode: "+886", flag: "🇹🇼" },
  { name: "Tajikistan", nationality: "Tajik", isoCode: "TJ", phoneCode: "+992", flag: "🇹🇯" },
  { name: "Tanzania", nationality: "Tanzanian", isoCode: "TZ", phoneCode: "+255", flag: "🇹🇿" },
  { name: "Thailand", nationality: "Thai", isoCode: "TH", phoneCode: "+66", flag: "🇹🇭" },
  { name: "Togo", nationality: "Togolese", isoCode: "TG", phoneCode: "+228", flag: "🇹🇬" },
  { name: "Tonga", nationality: "Tongan", isoCode: "TO", phoneCode: "+676", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", nationality: "Trinidadian/Tobagonian", isoCode: "TT", phoneCode: "+1-868", flag: "🇹🇹" },
  { name: "Tunisia", nationality: "Tunisian", isoCode: "TN", phoneCode: "+216", flag: "🇹🇳" },
  { name: "Turkey", nationality: "Turkish", isoCode: "TR", phoneCode: "+90", flag: "🇹🇷" },
  { name: "Turkmenistan", nationality: "Turkmen", isoCode: "TM", phoneCode: "+993", flag: "🇹🇲" },
  { name: "Tuvalu", nationality: "Tuvaluan", isoCode: "TV", phoneCode: "+688", flag: "🇹🇻" },
  { name: "Uganda", nationality: "Ugandan", isoCode: "UG", phoneCode: "+256", flag: "🇺🇬" },
  { name: "Ukraine", nationality: "Ukrainian", isoCode: "UA", phoneCode: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", nationality: "Emirati", isoCode: "AE", phoneCode: "+971", flag: "🇦🇪" },
  { name: "Uruguay", nationality: "Uruguayan", isoCode: "UY", phoneCode: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", nationality: "Uzbekistani", isoCode: "UZ", phoneCode: "+998", flag: "🇺🇿" },
  { name: "Vanuatu", nationality: "Vanuatuan", isoCode: "VU", phoneCode: "+678", flag: "🇻🇺" },
  { name: "Venezuela", nationality: "Venezuelan", isoCode: "VE", phoneCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", nationality: "Vietnamese", isoCode: "VN", phoneCode: "+84", flag: "🇻🇳" },
  { name: "Yemen", nationality: "Yemeni", isoCode: "YE", phoneCode: "+967", flag: "🇾🇪" },
  { name: "Zambia", nationality: "Zambian", isoCode: "ZM", phoneCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", nationality: "Zimbabwean", isoCode: "ZW", phoneCode: "+263", flag: "🇿🇼" },
];

export default COUNTRIES;